version: '3'
services:
  discoveryserver:
    container_name: discovery_server
    image: discoveryserver:2.0
#    restart: always
    ports:
      - "8761:8761"
    expose:
      - "8761"
  apigateway:
    container_name: api_gateway
    image: apigateway:2.0
#    restart: always
    depends_on:
      - discoveryserver
    ports:
      - "80:80"
    expose:
      - "80"
  inventorymanagement:
    container_name: inventory_management
    image: inventorymanagement:2.0
#    restart: always
    depends_on:
      - apigateway
      - discoveryserver
  usermanagement:
    container_name: user_management
    image: usermanagement:2.0
#    restart: always
    depends_on:
      - apigateway
      - discoveryserver
  orderplacement:
    container_name: order_placement
    image: orderplacement:2.0
#    restart: always
    depends_on:
      - apigateway
      - discoveryserver
  identitymanagement:
    container_name: identity_management
    image: identitymanagement:2.0
#    restart: always
    depends_on:
      - apigateway
      - discoveryserver
